### ISSUE TITLE
examples fail

### ISSUE THREAD

**Issue by TBD** [pendragon-andyh/tony.js#1]
with error
`Uncaught TypeError: Failed to execute 'start' on 'AudioBufferSourceNode': The provided double value is non-finite.`

**Comment by pendragon-andyh** [comment]
Fixed.  Looks like Chrome has changes the behaviour of the AudioBufferSourceNode when it is presented with undefined values for the 2nd and 3rd arguments for the start method.

Please note that this project is obsolete now.  The Web Audio API will soon be changing its method of creating new audio nodes - which would break the techniques used in this project.
